[package]
name = "nero-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
age = "0.12.1"
base64 = "0.23.1"
comrak = "0.56"
notify = "8.2"
rusqlite = { version = "0.40", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.11"
zip = "8.6"
